name: pyfar
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.23.0
  - matplotlib
  - scipy>=1.5.0
  - libsndfile
  - pip:
    - urllib3
    - deepdiff
    - soundfile>=0.11.0
    - sofar==0.3.1
    - pyfar
